### PR TITLE
Added Card UI in page Introduction to Open Source

### PR DESCRIPTION
**Pull request by Greyash-Dave**
## Category

- [ ] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [ ] User Interface
- [ ] Feature Addition

## Related Issue

Fixes #XX

## Checklist

- [ ] I have followed the [CONTRIBUTING](https://github.com/Sriparno08/Start-Contributing/blob/main/CONTRIBUTING.md) guide
- [ ] The name of the resource is spelled correctly (if applicable)
- [ ] The link to the resource is working (if applicable)
- [ ] The resource is added in the correct format (if applicable)
- [ ] I have tested changes on my local computer (if applicable)

### CODE REVIEW

**Comment by Greyash-Dave** [comment]
I Have made the changes to the best of my ability, hope you like it. Also there seems to be a conflict in app.js which are 2 lines which u could manually change instead it allows you to get three cards in a row as you requested

**Comment by Greyash-Dave** [comment]
did you retweak the design of the cards or was that what you received in the PR because this was the design i implmented:

op1

**Comment by Sriparno08** [comment]
Yeah, @Greyash-Dave. I modified your design a little bit according to my preference.

**Comment by Greyash-Dave** [comment]
could I next add the same card element you retweaked to  Learn Git and GitHub page

**Comment by Sriparno08** [comment]
Hey @Greyash-Dave, let's keep this design to the applied page for now as it may be changed later. Once I finish deciding the final design, I'll probably implement it in other category pages.

**Comment by Greyash-Dave** [comment]
Is there any page to work on if so can you mention it, or is there any UI improvements needed like the card design you mention previously, I am a bit free to work till 15-08-24, any work given I will try to my best ability.

**Comment by Sriparno08** [comment]
Hey @Greyash-Dave, I'm currently trying to find any improvements that can be made in any of the pages. IF I find any, I'll open an issue on it.

**Pull request merged**
