### PR TITLE
Issue 197 Fixed

### LINKED ISSUE #197: Add a new open source programme in SOC
## Category

- [ ] Documentation
- [x] Resource Addition
- [ ] Codebase
- [ ] User Interface
- [ ] Feature Request

## Description

I wanted to add some more open source programmes in SOC section
- XROS

## Open-source
I'm contributing under JWOC

### PR DESCRIPTION
**Pull request by yusra05**
## Description

A new Open source Program added in Season of Code ( SOC ) section.
image

## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [ ] User Interface
- [x] Feature Request

## Related Issue
Fixes #197 

## Checklist

- [x] I have gone through the [CONTRIBUTING](https://github.com/Sriparno08/Start-Contributing/blob/main/CONTRIBUTING.md) guide
- [x] The name of the resource is spelled correctly (if applicable)
- [x] The link to the resource is working (if applicable)
- [x] The resource is added in the correct format (if applicable)
- [x] I have tested changes on my local computer (if applicable)

### CODE REVIEW

**Review by Sriparno08 — APPROVED** [review]
Looks good 👍

**Comment by yusra05** [comment]
Can i add more open-source programmes?

**Comment by Sriparno08** [comment]
Yes, but make sure you open separate issues for each one.

**Comment by yusra05** [comment]
Okay

**Pull request merged**
