### PR TITLE
Added Animation Styles to Navbar and Get Start Button

### LINKED ISSUE #136: [FIX]: Nav bar and get started button styling
## Category

- [x] Documentation
- [x] User Interface
-

## Description

The Nav bar and the get started button should be more appealing and attractive. JWOC

img

### PR DESCRIPTION
**Pull request by zul132**
## Description
I have added some animation styles to the links in the Navbar as well as the Get Started button, in order to make the UI more attractive and appealing. 

### Change 1: Button hover animation
I have implemented a simple animation for the Get Started button to expand by 15% on hover, since the Page is mostly static and this hover effect will make the button more dynamic and engaging.

openpedia_2

openpedia_1

### Change 2: links 3D Animation 
For the "About" and "GitHub" links, I added a 3D effect to each link by translating the link horizontally when hovered.

openpedia_3

openpedia_4

### Change 3: Title size transformation
I converted the "Openpedia" title into a link directed back to the Landing page (in this case the same page), and added a CSS Transformation effect to expand the title font from 20px to 23px on detecting a mouse hover. The title shrinks back to its original size when the mouse is removed.

openpedia_5

openpedia_6

P.S: The reason for converting the title into a link for the Landing page is because I noticed that you've assigned some issues for creating new pages for the categories like "Introduction to Open Source" page, as well as an FAQ page. Therefore, although the website at the moment is a single page website and doesn't really require this link, I believe it will be handy to have once the other web pages are added, allowing the visitor to navigate back-and-forth to the Landing page.

## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Related Issue

Fixes #136 

## Checklist

- [x] I have gone through the [CONTRIBUTING](https://github.com/Sriparno08/Start-Contributing/blob/main/CONTRIBUTING.md) guide
- [ ] The name of the resource is spelled correctly (if applicable)
- [ ] The link to the resource is working (if applicable)
- [ ] The resource is added in the correct format (if applicable)

### CODE REVIEW

**Comment by zul132** [comment]
@Sriparno08 Kindly take a look at my changes and let me know if you liked them. Also, inform me if there's any particular styles that you want to be added to the Navbar and header section, I can make the required modifications and create another PR (if needed)

**Comment by Sriparno08** [comment]
Nice changes, @zul132. Here is my feedback:

1. The scaling animation looks good. But for now, let's keep the original animation as it's looking engaging enough.
2. The background color on hover is a great choice. The only change to do here is removing the translate property on hover as the original position is looking better.
3. The link added to the title is a great addition. Just don't increase the size of it on hover as the original size is looking better.

**Comment by zul132** [comment]
Got it. Should I create a new pull request after making the specified changes?

**Comment by zul132** [comment]
@Sriparno08  I've made the suggested changes and pushed the code. Can my PR be merged now?

**Comment by Sriparno08** [comment]
Your PR is merged 👍

**Pull request merged**
