### PR TITLE
Add Learn Github Page

### LINKED ISSUE #157: Feat: Create a 'Learn Git & GitHub' Page
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [ ] User Interface
- [x] Feature Request

## Description

We need to create a 'Learn Git & GitHub' page:

- Keep the theme intact
- Add some placeholder entries to the page as resources as the real ones will be dynamically inserted later
- The way in which each resource will show up is up to you

**For Assignee:**

> Ensure that you submit a PR for this issue within 4 days. Otherwise, you will be unassigned from this issue and it will be passed on to the next contributor who asked to be assigned to it.

_Note: This issue is for JWoC 2024 participants. If you are not participating in this event, please refrain from asking to get assigned to this issue._

### PR DESCRIPTION
**Pull request by prasukjain07**
## Description

Fixes #157 

## Category

- [x] Documentation
- [x] Resource Addition
- [x] Codebase
- [x] User Interface
- [x] Feature Request

## Related Issue

Fixes #XX

## Checklist

- [x] I have gone through the [CONTRIBUTING](https://github.com/Sriparno08/Start-Contributing/blob/main/CONTRIBUTING.md) guide
- [x] The name of the resource is spelled correctly (if applicable)
- [x] The link to the resource is working (if applicable)
- [x] The resource is added in the correct format (if applicable)
- [x] I have tested changes on my local computer (if applicable)

### CODE REVIEW

**Comment by Sriparno08** [comment]
Good work, @prasukjain07.

In the coming stages, we may create a FAQ section exclusive to this page and add all of these Q&As to this section.

For now, we only want to display the resources on this page that correspond to the topic. So, please remove the Q&As and add the resources to the page.

**Comment by prasukjain07** [comment]
Please check

**Comment by Sriparno08** [comment]
Next Steps:

1. Remove the 'Home' & 'Learn Git' links from the landing page navbar
2. Remove `color: white` & `text-align: center` from `footer` in client/styles.css
3. Remove the `br` element after `main div` in client/git/index.html
4. Make the footer in the 'Learn Git & GitHub' page look exactly the same as the landing page looks after making the above suggested modifications
5. Since you made changes to the 'FAQ' page, you can make the navbar and footer of this page look exactly the same as the landing page looks after making the above suggested modifications

**Review by Sriparno08 — APPROVED** [review]
Looks good 👍

**Pull request merged**
