### PR TITLE
Added a feature Rate Us.

### LINKED ISSUE #544: [Feature Addition] <Addition of a Feature Of Rate Us!!>
## Category

- [ ] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [ ] User Interface
- [x] Feature Addition

## Description

I noticed that the feedback of user is also a necessary component to know what is needed in the website. Hence adding an option of rating using stars for the users will help us to have a nice feedback database. I would love to create a feature as such for your website.

### PR DESCRIPTION
**Pull request by SrishtiChamoli**
## Description

This PR introduces a new "Rate Us" feature to encourage user feedback. Users can now click a "Rate Us" button.
This Rate Us Column appears in the center of the screen as soon as it past 30 seconds of surfing on the website. Ensures user input and interest of the user towards the website.

## Category

- [ ] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [ ] User Interface
- [x] Feature Addition

## Related Issue

Fixes #544 

## Checklist

- [x] I have followed the [CONTRIBUTING](https://github.com/Sriparno08/Start-Contributing/blob/main/CONTRIBUTING.md) guide
- [x] The name of the resource is spelled correctly (if applicable)
- [x] The link to the resource is working (if applicable)
- [x] The resource is added in the correct format (if applicable)
- [x] I have tested changes on my local computer (if applicable)

### CODE REVIEW

**Comment by Sriparno08** [comment]
Nice addition, @SrishtiChamoli!

I have two suggestions regarding this feature:

S1: Currently, the star that is hovered is glowing, whereas the other ones are not. My preference is that, if a star is hovered, it will glow along with the stars before it. For example, if we hover on the 4th star, it will glow along with the previous three stars.

S2: We can add a border when the 'Submit Rating' button is hovered to differentiate it from the background as it currently almost blends with the background when hovered.

**Comment by SrishtiChamoli** [comment]
Okay!! nice ideas...I'll look into it and get back to you!

**Comment by SrishtiChamoli** [comment]
I've made the changes as directed by you. Let me know in case of any other rectifications!!

**Review by Sriparno08 — APPROVED** [review]
Great job, @SrishtiChamoli!

**Pull request merged**
