### PR TITLE
Normalised card height and added spacing in open source programs (responsive)

### PR DESCRIPTION
**Pull request by Greyash-Dave**
## Category

- [ ] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [ ] User Interface
- [ ] Feature Addition

## Related Issue

Fixes #XX

## Checklist

- [ ] I have followed the [CONTRIBUTING](https://github.com/Sriparno08/Start-Contributing/blob/main/CONTRIBUTING.md) guide
- [ ] The name of the resource is spelled correctly (if applicable)
- [ ] The link to the resource is working (if applicable)
- [ ] The resource is added in the correct format (if applicable)
- [ ] I have tested changes on my local computer (if applicable)

### CODE REVIEW

**Comment by Greyash-Dave** [comment]
this applies only if Normalised card hide and added spacing in open source programs has been merged

**Review by Sriparno08 — APPROVED** [review]
Looks good, @Greyash-Dave! 👍

**Comment by Greyash-Dave** [comment]
If there is any other UI improvements Needed, you could send me a design like the time you sent for the card element, I will try my best implementing it

**Comment by Sriparno08** [comment]
Hey @Greyash-Dave, I'm currently going for different designs in the category pages to find out the one that looks the best to me. So no, the card swiping design is not finalized yet.

**Pull request merged**
