### PR TITLE
[ISSUE-146] Modify NavBar: Complete, Responsive, and Themed

### LINKED ISSUE #146: Feat: Update Navbar UI & Add Custom Scrollbar
## Category

- [x] Codebase
- [x] User Interface Enhancements
- [x] Feature Request

## Description

I would like to update the UI of navbar. I intend to make the navbar sticky, enhance it with features such as box-shadow, improved text styles, hover effects and other Modern UI trends. Additionally, I would like to incorporate a custom scrollbar into the website.

- Modern UI such as:
Until someone scrolls on the website, the navbar's background will remain transparent with a border. Upon scrolling, it will become sticky, and its appearance will be filled with a theme color & backdrop blur effect.

Can you please assign this issue to me under JWOC.

### PR DESCRIPTION
**Pull request by antilneeraj**
## Description

This commit addresses issue #146 by implementing modifications to the NavBar. The changes ensure that the NavBar is now complete, responsive, and follows a cohesive theme, enhancing the overall user experience.

## Related Issue

- Fixes #146

## Category

- [x] Responsive Design
- [x] Themed Integration
- [x] Proper Routing of Pages
- [x] Feature Request

## Screenshots

I have attached screenshots of NavBar to provide a visual representation of the changes. Feel free to review and provide feedback.

## Additional Notes

I have thoroughly tested the functionality and appearance of NavBar to ensure a smooth user experience. If there are any specific areas that require attention or if you have additional feedback, please let me know.

## Checklist

- [x] I have gone through the [CONTRIBUTING](https://github.com/Sriparno08/Start-Contributing/blob/main/CONTRIBUTING.md) guide
- [x] The name of the resource is spelled correctly
- [x] The link to the resource is working
- [x] The resource is added in the correct format

### CODE REVIEW

**Comment by antilneeraj** [comment]
@Sriparno08 This pull request is ready for review and merge. Thank you for the opportunity to contribute!

**Comment by Sriparno08** [comment]
Nice additions, @antilneeraj. Here is my feedback:

1. Let's keep the original background color of the navbar
2. Change the value of `opacity` from `0.5` to `1`
3. Let's remove the box shadow. It's a good addition, but we currently don't want to apply it to the navbar
4. The sticky effect is looking good, so we're keeping it.

**Comment by antilneeraj** [comment]
Hi @Sriparno08 ,

Thanks for your feedback! I've made the requested changes:

[x] Kept the original background color of the navbar.
[x] Updated the opacity value from 0.5 to 1.
[x] Removed the box shadow as per your suggestion.
I'm glad to hear that the sticky effect is looking good and has been retained.

Let me know if there's anything else you'd like me to adjust. Appreciate your guidance!

**Comment by antilneeraj** [comment]
Additionally, I kindly request you to consider adding the "JWOC" and "Difficulty" labels to this pull request.

**Review by Sriparno08 — APPROVED** [review]
Looks good 👍

**Pull request merged**
