### PR TITLE
Adding more focus to the card element by differentiating it from the webpage background in introduction-to-open-source page

### PR DESCRIPTION
**Pull request by Greyash-Dave**
## Category

- [ ] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [ ] User Interface
- [ ] Feature Addition

## Related Issue

Fixes #XX

## Checklist

- [ ] I have followed the [CONTRIBUTING](https://github.com/Sriparno08/Start-Contributing/blob/main/CONTRIBUTING.md) guide
- [ ] The name of the resource is spelled correctly (if applicable)
- [ ] The link to the resource is working (if applicable)
- [ ] The resource is added in the correct format (if applicable)
- [ ] I have tested changes on my local computer (if applicable)

### CODE REVIEW

**Comment by Greyash-Dave** [comment]
check if this design is to your liking, as well as a reply if you like to add a swipperjs funtionality to slide the cards instead of viewing all cards at once i think it will be more presentable, if you like the idea i will PR it next

**Comment by Sriparno08** [comment]
Hey @Greyash-Dave, the design looks good. However, my preference is:

- The cards will have a background color of `rgb(25, 50, 84)`
- The container that contains all the cards won't have a background color

So, you can implement the above things.

In terms of swipe functionality, we can go ahead with it. Let's include 9/12 cards in each page. We can do something like the following:

image

**Comment by Greyash-Dave** [comment]
Type one:
sc2

Type two:
sc1

choose which is to your linking, 

as well as could you mention that did you mean to change the card background 
current: background: linear-gradient(135deg, rgb(153, 247, 153), rgb(102, 204, 255));
to: rgb(25, 50, 84)

and could you elaborate on  9/12 as i couldn't understand

**Comment by Sriparno08** [comment]
Yes, @Greyash-Dave. I suggested to change the card background to `rgb(25, 50, 84)` and the background of both the article and video containers from `#193254` to `transparent`.

Also, let's include 2 or 3 rows (instead of 1) with each row having 3 resources (instead of 4) and place the slider in the bottom, as it is in the sample that I shared.

**Comment by Sriparno08** [comment]
Hey @Greyash-Dave, all your changes are implemented using the other two PRs. So, I'm closing this one.

**Pull request closed without merging**
