### PR TITLE
[UI] Update Git Resources Section

### LINKED ISSUE #548: [UI] Improving the Resources Section in "Learn Git and Github" Page Using Carousel
Description : Update the "Resources" section on the Learn Git and GitHub page by adding a carousel similar to the one on the Introduction to Open Source page.

- [ ] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [x] User Interface
- [ ] Feature Addition

Expected Outcome The "Resources" section in "Learn Git and Github" is more interactive and visually engaging, allowing users to browse through resources easily.

Priority & Deadline : High &  21/10/24

### PR DESCRIPTION
**Pull request by tharagaramanbalaji**
## Description

This pull request introduces a carousel to the Git & GitHub resources section using the Swiper library. The following changes were made to enhance the user experience and provide a clean, interactive way to navigate through the resources.

## Changes Made:

- Carousel Implementation: Integrated the Swiper library to create a responsive carousel for the resources section.

- Color Theme: Followed a consistent color theme for the carousel items to match the overall UI design of the page.

- Arrow Buttons and Pagination: Added neat and intuitive arrow buttons for navigation and implemented pagination for easy access to specific items within the carousel.

- Hover Effects and Animations: Enhanced user interaction by adding hover effects on carousel items and also included smooth animations to improve the overall visual appeal.

Before : 
image

After :
image

## Category

- [ ] Resource Addition
- [ ] Documentation
- [ ] Codebase
- [x] User Interface
- [ ] Feature Addition

## Related Issue

Fixes #548 

## Checklist

- [x] I have followed the [CONTRIBUTING](https://github.com/Sriparno08/Start-Contributing/blob/main/CONTRIBUTING.md) guide
- [x] I have tested changes on my local computer (if applicable)

### CODE REVIEW

**Comment by Sriparno08** [comment]
Good work, @tharagaramanbalaji.

As per my preference:

1. Can you include 3 rows in each slide with each row containing 3 resources?
2. Can you change the slider design to match the one in the 'Introduction to Open Source' Page?

Here is a design for your reference while executing the first suggestion:


image

**Comment by tharagaramanbalaji** [comment]
Alright @Sriparno08 will make the necessary changes as you mentioned 🙌🙌

**Comment by tharagaramanbalaji** [comment]
@Sriparno08 any other to make let me know...commited with required changes

**Review by Sriparno08 — APPROVED** [review]
Good work, @tharagaramanbalaji. Made some changes from my side as well to match the design with my preference.

Now, the changes look good to be merged.

**Comment by tharagaramanbalaji** [comment]
Thank you for making the necessary changes and merging the pr @Sriparno08

**Pull request merged**
