### PR TITLE
Changed the 'Contribute' section description. 

### LINKED ISSUE #127: Chore: Change 'Contribute' Description in Landing Page
## Description

We need to change the 'Contribute' section description in landing page by replacing the current one with the following one:

> Openpedia is waiting for your contribution! There are many ways that you can contribute to this project, such as improving the documentation, adding resources, enhancing the codebase and more.

**For Assignee:**

> Ensure that you submit a PR for this issue within 1 day. Otherwise, you will be unassigned from this issue and it will be passed on to the next contributor who asked to be assigned to it.

_Note: This issue is for JWoC 2024 participants. If you are not participating in this event, please refrain from asking to get assigned to this issue._

### PR DESCRIPTION
**Pull request by Isha1031**
Adding my name to the contributor list by changing the description of the 'Contribute' section on the landing page.

Fixes #127

### CODE REVIEW

**Comment by antilneeraj** [comment]
Hi Isha,
I think that the time period is not static like 24 hours as per your description to Contribut Section of home page. As the time assignment totally depends on the mentors point of view about the expected time and complexity of work assigned...

So the description could be :
To maintain a smooth and efficient development process, we request that you submit a Pull Request(PR) for this issue **within the specified deadline**. Your expertise and contributions are invaluable to the project's success, and we're grateful for your commitment.

**Comment by Isha1031** [comment]
Ok sir, I will change that. Thank you for guiding.

**Comment by Isha1031** [comment]
Changed the 24 hrs timeline to the deadline, which will be specified by the mentor.

**Comment by Sriparno08** [comment]
Hey @Isha1031, you might have gotten it incorrectly. Here is the text that you need to insert instead of the current one:

Openpedia is waiting for your contribution! There are many ways that you can contribute to this project, such as improving the documentation, adding resources, enhancing the codebase and more.

**Comment by Isha1031** [comment]
Okay sir... Sorry... Will correct it

**Comment by Sriparno08** [comment]
Hey @Isha1031, please update the PR with the required changes as soon as possible. Otherwise, you will be unassigned from the corresponding issue.

**Comment by Isha1031** [comment]
I have updated it sir but I don't know why the changes are not being
committed yet

**Comment by Isha1031** [comment]
Sir i made the changes but am not able to create PR please help

**Review by Sriparno08 — APPROVED** [review]
Looks good 👍

**Pull request merged**
